### ISSUE TITLE
Tokens are not working for me (Vite + Vue 3 )

### ISSUE THREAD

**Issue by zaidchauhan** [Tahul/pinceau#107]
I have been experimenting with the Pinceau library and encountered an issue where the styles from tokens.config.ts are not being applied in the browser.

I have carefully read the documentation multiple times to ensure proper configuration.
Any suggestions, feedback, or help in resolving this issue would be greatly appreciated.

**Issues**:

- The browser DevTools indicate that --color-black is not defined.
- Interestingly, VSCode IntelliSense recognizes the token perfectly well.

Despite thoroughly reviewing the documentation and ensuring correct configuration, the issue persists. I am looking for any assistance or feedback to understand what might be going wrong.

**Repository to Reproduce:**

https://github.com/zaidchauhan/pinceau-issue

**Steps to Reproduce:**

- Clone the provided repository
- Run npm install
- Run npm run dev

**Comment by Tahul** [comment]
Hey @zaidchauhan :)

Thank you for your interest in Pinceau and for your reproduction!

They only thing you are missing is `<pinceau />` tag in your `index.html`.

You can add it right here:
https://github.com/zaidchauhan/pinceau-issue/blob/e4c8d37000818a143ac654734f47fe2cbd91faef/index.html#L7

With that tag, the theme sheet will be injected in your app, and then your tokens will work as expected!

I also suggest to upgrade to `0.20.0` :)
