### ISSUE TITLE
$dt usage outside of vue

### ISSUE THREAD

**Issue by buischiomassimo** [Tahul/pinceau#22]
Use case: 
Let's say I am using Figma design tokens, pinceau and tailwindcss.
I'd like to be able to use Pinceau's directives such as $dt inside of tailwind.config.ts. Is this possible somehow?

**Comment by Tahul** [comment]
It is for sure possible!

Could you provide a reproduction env so I can point you out how to do it? :)

**Comment by Rigo-m** [comment]
https://stackblitz.com/edit/github-nhkc8j?file=tailwind.config.ts,nuxt.config.ts,.playground%2Fapp.vue,pinceau.config.ts
Here's a reproduction of what would be cool to be able to achieve.

**Comment by Tahul** [comment]
Hello @Rigo-m ;

Thank you a lot for the reproduction.

I will implement a way of achieving that very soon, let's track it here :)

**Comment by Tahul** [comment]
Should work anywhere since `^0.13.x`

**Comment by Rigo-m** [comment]
Great! Is this documented somewhere? Can't find it
