### ISSUE TITLE
Is Pinceau Supporting >=Vue2.7?

### ISSUE THREAD

**Issue by sor4chi** [Tahul/pinceau#23]
Hello, I'm a new member of the group. Thank you for providing us with a great product.
I have a few questions. I would be a newbie so sorry if I said something out of line.
Also, I'm not good at English, so sorry if it's hard to understand you.

I'm developing UI libraries using @vitejs/plugin-vue2, vue2.7, and @storybook/builder-vite.
In my storybook,  to set `<link rel="stylesheet" href="./node_modules/.vite/pinceau/index.css" />` in `preview-head.html` and `config.plugins.push(pinceau())` in `viteFinai(config)` is work for me.
But the build(`vite build`) fails.

questions:
- Is it possible to use pinceau with vue2?
- Are there any better solution to use pinceau in the storybook?

**Comment by Tahul** [comment]
I'm afraid it might be impossible to run it with Vue 2.7, yet I would love to look at your repo to check it out!

Could you provide me with a reproduction?

**Comment by sor4chi** [comment]
> I'm afraid it might be impossible to run it with Vue 2.7, yet I would love to look at your repo to check it out!
> 
> Could you provide me with a reproduction?

Sorry, the project is the library is for internal use only, so it cannot be made public.

For reproduction, I'll prepare a similar environment in another repository, so wait a moment
