### ISSUE TITLE
`runtime` option to `false` throws when rendering

### ISSUE THREAD

**Issue by stafyniaksacha** [Tahul/pinceau#59]
Setting `runtime` module option to false throw with `'.nuxt/pinceau-nuxt-plugin.client.mjs' does not provide an export named 'default'`

```ts
export default defineNuxtConfig({
  pinceau: {
    runtime: false,
  },
})
```

**Comment by Tahul** [comment]
hey :)

Should be resolved by https://github.com/Tahul/pinceau/commit/5dcacfefda4723f70f4bdadf4f2f7f84fa8205d7

Feel free to reopen (with a reproduction 🙏) if needed!
