### ISSUE TITLE
Error using playground

### ISSUE THREAD

**Issue by ollipiet** [Tahul/pinceau#6]
I have tried to load the playground, but it does not display anything. Is there some setup missing, or is it supposed to be blank?

Issue: Stackblitz playground is not showing anything after loading the environment. (404 error).

**Comment by Tahul** [comment]
Hey!

The playground seem fixed now!

As it grabs latest commit of Pinceau whenever you open it, you might have landed on a broken commit!

Could you confirm it's working for you now?

**Comment by ollipiet** [comment]
Hi, I can confirm that the latest commit does work now.
