### ISSUE TITLE
ts-error from computed

### ISSUE THREAD

**Issue by SGAMERyu** [Tahul/pinceau#61]
![image](https://user-images.githubusercontent.com/17926105/217015028-f682a1e8-4427-4666-b3b9-194018976e2e.png)

Implicit conversion of a 'symbol' to a 'string' will fail at runtime. Consider wrapping this expression in 'String(...)

**Comment by SGAMERyu** [comment]
In general, css properties should not have symbol and boolean types. Perhaps we should change the type definition of FunctionType

**Comment by Tahul** [comment]
Good call man, thanks a lot!
