### ISSUE TITLE
Migrate to magicast

### ISSUE THREAD

**Issue by pi0** [Tahul/pinceau#78]
Thanks for beta testing paneer 💛 It is now public as [unjs/magicast](https://github.com/unjs/magicast).

**Comment by Tahul** [comment]
Hey @pi0 ; thanks for the reminder!

I'll be closing this right now.

I'm sorry I left a bit the issues aside lately on Pinceau as I was working on #95 before going forward.

**Comment by Tahul** [comment]
I think I already dropped the dependency, just forgot to remove it from `package.json`, I'm sorry. 🤦

**Comment by Tahul** [comment]
Resolved in fb9231795265f7b2e2cdfb7cc7314c8c6f20fc7c :)
